---
version: "2.1"
services:
  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz
    container_name: netbootxyz
    volumes:
      - config:/config # optional
      - assets:/assets # optional
    ports:
      - 3000:3000
      - 69:69/udp
      - 8080:80 #optional
    restart: unless-stopped

volumes:
  config:
    external: true
    name: pxe-config
  assets:
    external: true
    name: pxe-assets