---
version: "3.7"
services:
  netbootxyz:
    image: lscr.io/linuxserver/netbootxyz:latest
    # image: ghcr.io/netbootxyz/netbootxyz:latest
    container_name: netbootxyz
    environment:
      - PUID=1026
      - PGID=65537
      - TZ=Europe/Bucharest
      - MENU_VERSION=1.9.9 #optional
      - PORT_RANGE=30000:30010 #optional
      - SUBFOLDER=/ #optional
    volumes:
      - type: bind
        source: $PXE_CONFIG
        target: /config
      - type: bind
        source: $PXE_DATA
        target: /assets
    ports:
      - 3000:3000
      - 69:69/udp
      - 8080:80 #optional
    restart: unless-stopped

volumes:
  config:
    external: true
    name: pxe-config
  assets:
    external: true
    name: pxe-assets
