version: "3"

services:
  cs16:
    image: archont94/counter-strike1.6
    restart: always
    ports:
      - 27015:27015
      - 27015:27015/udp
    volumes:
      - cs_data:/hlds
    environment:
      - SERVER_NAME=TeBatCuLingura's server
      - MAX_PLAYERS=10
      - ADMIN_STEAM_ID
    logging:
      driver: "json-file"
      options:
        max-size: "5m"

volumes:
  cs_data:
    external: true
    name: cs_data

