version: "3"

services:
  cs16:
    image: archont94/counter-strike1.6
    restart: always
    ports:
      - 27015:27015
      - 27015:27015/udp
    volumes:
      - cs_data:/hlds
    logging:
      driver: "json-file"
      options:
        max-size: "5m"

volumes:
  cs_data:
    external: true
    name: cs_data

