version: "3"

services:
  unifi:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-controller
    environment:
      - PUID=1026
      - PGID=65537
      - TZ=Europe/Bucharest
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
    volumes:
      - type: bind
        source: $UNIFI_HOST_PATH
        target: /config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8082:8080
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped
