version: "3"

services:
  unifi-db:
    image: docker.io/mongo:4.4
    container_name: unifi-db
    environment:
      - PUID=1026
      - PGID=65537
      - MONGO_PASS
    volumes:
      - $UNIFI_DB_HOST_PATH:/data/db
      - $UNIFI_DB_INIT_HOST_PATH/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    restart: unless-stopped
    networks:
      - home-net

  unifi:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-controller
    environment:
      - PUID=1026
      - PGID=65537
      - TZ=Europe/Bucharest
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
      - MONGO_USER=unifi
      - MONGO_PASS
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
    volumes:
      - type: bind
        source: $UNIFI_HOST_PATH
        target: /config
#    ports:
#      - 8443:8443
#      - 3478:3478/udp
#      - 10001:10001/udp
#      - 8080:8080
#      - 1900:1900/udp #optional
#      - 8843:8843 #optional
#      - 8880:8880 #optional
#      - 6789:6789 #optional
#      - 5514:5514/udp #optional
    networks:
      home-net:
      macvlan_network:
        ipv4_address: 192.168.2.2
    restart: unless-stopped

networks:
  home-net:
    name: home-net
  macvlan_network: 
    name: macvlan-br0
    external: true