version: "3"

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    volumes:
      - type: bind
        source: $JELLYFIN_CONFIG_PATH
        target: /config
      - type: bind
        source: $MOVIES_HOST_PATH
        target: /data/movies
      
    restart: 'unless-stopped'
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0

    environment:
      - JELLYFIN_PublishedServerUrl=http://jellyfin.home.tbcl.ro
      - PUID=1026
      - PGID=65537
