version: "3"

services:
  server:
    image: itzg/minecraft-server
    environment:
      - VERSION=1.20.4
      - INIT_MEMORY=1G
      - MAX_MEMORY=2G
      - EULA=TRUE
      - TYPE=SPIGOT
      - ENFORCE_WHITELIST=TRUE
      - ENABLE_WHITELIST=TRUE
      - MAX_PLAYERS=10
      - VIEW_DISTANCE=10
      - FORCE_GAMEMODE=true
      - MODE=survival
      - NETWORK_COMPRESSION_THRESHOLD=-1
      - TZ=Europe/Bucharest
      - BUILD_FROM_SOURCE=true
      - GENERATE_STRUCTURES=true
    tty: true
    stdin_open: true
    restart: always
    ports:
      - 25565:25565
    volumes:
      - test-world:/data
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
  backups:
    image: itzg/mc-backup
    environment:
      BACKUP_INTERVAL: "2h"
      RCON_HOST: server
      PRE_BACKUP_SCRIPT: |
        echo "Before backup!"
      PAUSE_IF_NO_PLAYERS: true
      PLAYERS_ONLINE_CHECK_INTERVAL: "1h"
      PRUNE_BACKUPS_DAYS: 7
      PRUNE_RESTIC_RETENTION: "--keep-daily 7 --keep-weekly 5 --keep-monthly 12 --keep-yearly 75"
      RESTIC_REPOSITORY: /backups
      RESTIC_PASSWORD:

    volumes:
      # mount the same volume used by server, but read-only
      - test-world:/data:ro
      # use a host attached directory so that it in turn can be backed up
      # to external/cloud storage
      - test-backup:/backups

volumes:
  test-world:
    external: true
    name: minecraft-test-world
  test-backup:
    external: true
    name: minecraft-test-world-backup
