version: "3"

services:
  server:
   image: itzg/minecraft-server
   environment:
     - VERSION=1.20.2
     - INIT_MEMORY=1G
     - MAX_MEMORY=2G
     - EULA=TRUE
     - TYPE=SPIGOT
     - ENFORCE_WHITELIST=TRUE
     - ENABLE_WHITELIST=TRUE
     - MAX_PLAYERS=10
     - VIEW_DISTANCE=10
     - FORCE_GAMEMODE=true
     - MODE=survival
     - NETWORK_COMPRESSION_THRESHOLD=-1
     - TZ=Europe/Bucharest
     - BUILD_FROM_SOURCE=true
     - GENERATE_STRUCTURES=true
   tty: true
   stdin_open: true
   restart: always
   ports:
     - 25565:25565
   volumes:
     - test-world:/data
   logging:
     driver: "json-file"
     options:
       max-size: "5m"

volumes:
  test-world:
    external: true
    name: minecraft-test-world
