version: '3.5'
services:
  postgres-server:
    image: postgres:15-alpine
    volumes:
     - ${ZBX_ENV_DIR}/var/lib/postgresql/data:/var/lib/postgresql/data:rw
     - ${ENV_VARS_DIR}/.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro
     - ${ENV_VARS_DIR}/.ZBX_DB_CERT_FILE:/run/secrets/server-cert.pem:ro
     - ${ENV_VARS_DIR}/.ZBX_DB_KEY_FILE:/run/secrets/server-key.pem:ro
    env_file:
     - ${ENV_VARS_DIR}/.env_db_pgsql
    secrets:
     - POSTGRES_USER
     - POSTGRES_PASSWORD
    stop_grace_period: 1m
    networks:
      zbx_net_backend:
        aliases:
         - postgres-server
         - pgsql-server
         - pgsql-database

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:ubuntu-6.4-latest
    ports:
     - "10051:10051"
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - ${ZBX_ENV_DIR}/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
     - ${ZBX_ENV_DIR}/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
     - ${ZBX_ENV_DIR}/var/lib/zabbix/dbscripts:/var/lib/zabbix/dbscripts:ro
     - ${ZBX_ENV_DIR}/var/lib/zabbix/export:/var/lib/zabbix/export:rw
     - ${ZBX_ENV_DIR}/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
     - ${ZBX_ENV_DIR}/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
     - ${ZBX_ENV_DIR}/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
     - ${ZBX_ENV_DIR}/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
     - snmptraps:/var/lib/zabbix/snmptraps:rw
#   - ${ENV_VARS_DIR}/.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro
#   - ${ENV_VARS_DIR}/.ZBX_DB_CERT_FILE:/run/secrets/client-cert.pem:ro
#   - ${ENV_VARS_DIR}/.ZBX_DB_KEY_FILE:/run/secrets/client-key.pem:ro
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    deploy:
      resources:
        limits:
          cpus: '0.70'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    env_file:
     - ${ENV_VARS_DIR}/.env_db_pgsql
     - ${ENV_VARS_DIR}/.env_srv
    secrets:
     - POSTGRES_USER
     - POSTGRES_PASSWORD
    depends_on:
     - postgres-server
    networks:
      zbx_net_backend:
        aliases:
          - zabbix-server
          - zabbix-server-pgsql
          - zabbix-server-ubuntu-pgsql
          - zabbix-server-pgsql-ubuntu
      zbx_net_frontend:
#  devices:
#   - "/dev/ttyUSB0:/dev/ttyUSB0"
    stop_grace_period: 30s
    sysctls:
      - net.ipv4.ip_local_port_range=1024 64999
      - net.ipv4.conf.all.accept_redirects=0
      - net.ipv4.conf.all.secure_redirects=0
      - net.ipv4.conf.all.send_redirects=0
    labels:
      com.zabbix.description: "Zabbix server with PostgreSQL database support"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-server"
      com.zabbix.dbtype: "pgsql"
      com.zabbix.os: "ubuntu"

  zabbix-web-nginx-pgsql:
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-6.4-latest
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ZBX_ENV_DIR}/etc/ssl/nginx:/etc/ssl/nginx:ro
      - ${ZBX_ENV_DIR}/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
#   - ${ENV_VARS_DIR}/.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro
#   - ${ENV_VARS_DIR}/.ZBX_DB_CERT_FILE:/run/secrets/client-cert.pem:ro
#   - ${ENV_VARS_DIR}/.ZBX_DB_KEY_FILE:/run/secrets/client-key.pem:ro
    deploy:
      resources:
        limits:
          cpus: '0.70'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    env_file:
      - ${ENV_VARS_DIR}/.env_db_pgsql
      - ${ENV_VARS_DIR}/.env_web
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    depends_on:
      - postgres-server
      - zabbix-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      zbx_net_backend:
        aliases:
          - zabbix-web-nginx-pgsql
          - zabbix-web-nginx-ubuntu-pgsql
          - zabbix-web-nginx-pgsql-ubuntu
      zbx_net_frontend:
    stop_grace_period: 10s
    sysctls:
      - net.core.somaxconn=65535
    labels:
      com.zabbix.description: "Zabbix frontend on Nginx web-server with PostgreSQL database support"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-frontend"
      com.zabbix.webserver: "nginx"
      com.zabbix.dbtype: "pgsql"
      com.zabbix.os: "ubuntu"

volumes:
  snmptraps:
  
networks:
  zbx_net_frontend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
  zbx_net_backend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24

secrets:
  POSTGRES_USER:
    file: ${ENV_VARS_DIR}/.POSTGRES_USER
  POSTGRES_PASSWORD:
    file: ${ENV_VARS_DIR}/.POSTGRES_PASSWORD