version: "3"

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - VIRTUAL_HOST=${RADARR_HOST}
      - VIRTUAL_PORT=7878
    volumes:
      - type: bind
        source: $RADARR_HOST_PATH
        target: /config
      - type: bind
        source: $MOVIES_HOST_PATH
        target: /downloads/movies
      - type: bind
        source: $DOWNLOADS_HOST_PATH
        target: /downloads/data
    networks:
      - web-internal
      - media-internal
    ports:
      - 7878:7878
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TRANSMISSION_WEB_HOME= #optional
      - USER=
      - PASS= #optional
      - WHITELIST= #optional
      - PEERPORT= #optional
      - HOST_WHITELIST= #optional

    volumes:
      - type: bind
        source: $TRANSMISSION_HOST_PATH
        target: /config
      - type: bind
        source: $MOVIES_HOST_PATH
        target: /downloads/movies
      - type: bind
        source: $DOWNLOADS_HOST_PATH
        target: /downloads/data
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    networks:
      - media-internal
    restart: unless-stopped

networks:
  web-internal:
    external: true
    name: web-internal
  media-internal:
    external: true
    name: media-internal
