version: "3"

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      prowlarr-config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - config-radarr:/config
      - movies:/movies

    ports:
      - 7878:7878
    restart: unless-stopped

volumes:
  config-radarr:
    external: true
    name: config-radarr
  movies:
    external: true
    name: movies
