version: "3"

services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - config-jackett:/config
    ports:
      - 9117:9117
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - config-radarr:/config
      - movies:/movies

    ports:
      - 7878:7878
    restart: unless-stopped

volumes:
  config-radarr:
    external: true
    name: config-radarr
  config-jackett:
    external: true
    name: config-jackett
  movies:
    external: true
    name: movies
