version: "3"

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1026
      - PGID=65537
      - TZ=Europe/Bucharest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.home.tbcl.ro`)"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.tls.certresolver=myresolver"
    volumes:
      - type: bind
        source: $RADARR_HOST_PATH
        target: /config
      - type: bind
        source: $MOVIES_HOST_PATH
        target: /media/movies
      - type: bind
        source: $DOWNLOADS_HOST_PATH
        target: /downloads
    networks:
      - web
      - media-internal
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.home.tbcl.ro`)"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.routers.sonarr.tls.certresolver=myresolver"
    environment:
      - PUID=1026
      - PGID=65537
      - TZ=Europe/Bucharest
    volumes:
      - type: bind
        source: $SONARR_CONFIG_PATH
        target: /config
      - type: bind
        source: $SHOWS_HOST_PATH
        target: /media/shows
      - type: bind
        source: $DOWNLOADS_HOST_PATH
        target: /downloads
    networks:
      - media-internal
      - web
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(`transmission.home.tbcl.ro`)"
      - "traefik.http.services.transmission.loadbalancer.server.port=9091"
      - "traefik.http.routers.transmission.entrypoints=websecure"
      - "traefik.http.routers.transmission.tls.certresolver=myresolver"
    environment:
      - PUID=1026
      - PGID=65537
      - TRANSMISSION_WEB_HOME= #optional
      - USER=
      - PASS= #optional
      - WHITELIST= #optional
      - PEERPORT= #optional
      - HOST_WHITELIST= #optional
      - TZ=Europe/Bucharest
    volumes:
      - type: bind
        source: $TRANSMISSION_HOST_PATH
        target: /config
      - type: bind
        source: $DOWNLOADS_HOST_PATH
        target: /downloads

    ports:
      - 51413:51413
      - 51413:51413/udp
    networks:
      - web
      - media-internal

    restart: unless-stopped

networks:
  web:
    name: web
    external: true
  media-internal:
    external: true
    name: media-internal
