version: "3"

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1026
      - PGID=65537
      - VIRTUAL_HOST=${RADARR_URL}
      - VIRTUAL_PORT=7878
      - TZ=Europe/Bucharest
    volumes:
      - type: bind
        source: $RADARR_HOST_PATH
        target: /config
      - type: bind
        source: $MOVIES_HOST_PATH
        target: /media/movies
      - type: bind
        source: $DOWNLOADS_HOST_PATH
        target: /downloads
    networks:
      - media-internal
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1026
      - PGID=65537
      - TZ=Europe/Bucharest
    volumes:
      - type: bind
        source: $SONARR_CONFIG_PATH
        target: /config
      - type: bind
        source: $SHOWS_HOST_PATH
        target: /media/shows
      - type: bind
        source: $DOWNLOADS_HOST_PATH
        target: /downloads
    ports:
      - 8989:8989
    networks:
      - media-internal
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1026
      - PGID=65537
      - TRANSMISSION_WEB_HOME= #optional
      - USER=
      - PASS= #optional
      - WHITELIST= #optional
      - PEERPORT= #optional
      - HOST_WHITELIST= #optional
      - TZ=Europe/Bucharest
    volumes:
      - type: bind
        source: $TRANSMISSION_HOST_PATH
        target: /config
      - type: bind
        source: $DOWNLOADS_HOST_PATH
        target: /downloads

    ports:
      - 51413:51413
      - 51413:51413/udp
    networks:
      - media-internal
    restart: unless-stopped

networks:
  media-internal:
    external: true
    name: media-internal
