version: "3"

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: config-radarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - config:/config
      - movies:/movies

    ports:
      - 7878:7878
    restart: unless-stopped

volumes:
  config-radarr:
    external: true
    name: config-radarr
  movies:
    external: true
    name: movies