version: "3"

services:
  discord-jira-bot:
    image: eblenert/discord-jira-bot
    restart: unless-stopped
    ports:
      - 80:3000
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jira.rule=Host(`jira.home.tbcl.ro`)"
      - "traefik.http.services.jira.loadbalancer.server.port=3000"
      - "traefik.http.routers.jira.entrypoints=websecure"
      - "traefik.http.routers.jira.tls.certresolver=myresolver"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"

networks:
  web:
    external: true
    name: web
