version: "3"

services:
  iperf:
    restart: unless-stopped
    container_name: iperf3-server
    image: networkstatic/iperf3
    commands: -s
    stdin_open: true
    tty: true
    ports:
      - 5201:5201