---
version: "2.1"
services:
  firefox:
    image: jlesage/firefox
    privileged: true
    container_name: firefox
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - config:/config
    ports:
      - 5800:5800
    shm_size: "1gb"
    restart: unless-stopped

volumes:
  config:
