version: "3"

services:
 creative:
   image: itzg/minecraft-server
   environment:
     - VERSION=1.19.4
     - INIT_MEMORY=2G
     - MAX_MEMORY=5G
     - EULA=TRUE
     - TYPE=SPIGOT
     - ENFORCE_WHITELIST=TRUE
     - ENABLE_WHITELIST=TRUE
     - MAX_PLAYERS=10
     - VIEW_DISTANCE=10
     - FORCE_GAMEMODE=true
     - MODE=creative
     - NETWORK_COMPRESSION_THRESHOLD=-1
     - TZ=Europe/Bucharest
     - BUILD_FROM_SOURCE=true
     - LEVEL_TYPE=flat
     - GENERATE_STRUCTURES=false
   tty: true
   stdin_open: true
   restart: always
    ports:
      - 25565:25565
   volumes:
     - creative-world:/data
   logging:
     driver: "json-file"
     options:
       max-size: "5m"

volumes:
  creative-world:
    external: true
    name: minecraft-creative-world
