version: "3"

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    logging:
      driver: "json-file"
      options:
        max-size: "5m"

  db:
    image: mariadb
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD
    volumes:
      - db-storage:/var/lib/mysql
    logging:
      driver: "json-file"
      options:
        max-size: "5m"

#  creative:
#    image: itzg/minecraft-server
#    environment:
#      - VERSION=1.19.4
#      - INIT_MEMORY=2G
#      - MAX_MEMORY=5G
#      - EULA=TRUE
#      - TYPE=SPIGOT
#      - ENFORCE_WHITELIST=TRUE
#      - ENABLE_WHITELIST=TRUE
#      - MAX_PLAYERS=10
#      - VIEW_DISTANCE=10
#      - FORCE_GAMEMODE=true
#      - MODE=creative
#      - NETWORK_COMPRESSION_THRESHOLD=-1
#      - TZ=Europe/Bucharest
#      - BUILD_FROM_SOURCE=true
#      - LEVEL_TYPE=flat
#      - GENERATE_STRUCTURES=false
#    tty: true
#    stdin_open: true
#    restart: always
#    volumes:
#      - creative-world:/data
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "5m"

  survival:
    image: itzg/minecraft-server
    environment:
      - VERSION=1.19.4
      - INIT_MEMORY=2G
      - MAX_MEMORY=5G
      - EULA=TRUE
      - TYPE=SPIGOT
      - DIFFICULTY=hard
      - ENFORCE_WHITELIST=TRUE
      - ENABLE_WHITELIST=TRUE
      - MAX_PLAYERS=10
      - VIEW_DISTANCE=10
      - ENABLE_COMMAND_BLOCK=false
      - FORCE_GAMEMODE=true
      - SPAWN_PROTECTION=4
      - TZ=Europe/Bucharest
      - NETWORK_COMPRESSION_THRESHOLD=-1
      - BUILD_FROM_SOURCE=true
      - MARIADB_SURVIVAL_PASSWORD
    tty: true
    stdin_open: true
    restart: always
    ports:
      - 19132:19132/udp
      - 19133:19133/udp
    volumes:
      - survival-world:/data
      - dynmap-web:/web
    logging:
      driver: "json-file"
      options:
        max-size: "5m"

  mc-router:
    image: itzg/mc-router
    restart: always
    ports:
      - 25565:25565
    command: --mapping=minecraft.tbcl.ro=survival:25565,survival.minecraft.tbcl.ro=survival:25565,creative.minecraft.tbcl.ro=creative:25565
    logging:
      driver: "json-file"
      options:
        max-size: "5m"

volumes:
  survival-world:
    external: true
    name: minecraft-survival-world
  dynmap-web:
    external: true
    name: minecraft-dynmap-web
  creative-world:
    external: true
    name: minecraft-creative-world
  db-storage:
    external: true
    name: minecraft-db-storage

networks:
  mc-net:
    name: mc-net
