version: "3"

services:
  nginx-dynmap:
    image: nginx:latest
    restart: unless-stopped
    networks:
      - web-internal
    volumes:
      - dynmap-web:/usr/share/nginx/html/
    environment:
      - VIRTUAL_HOST
      - VIRTUAL_PORT
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
    logging:
      driver: "json-file"
      options:
        max-size: "5m"

  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
      - 19132:19132/udp
      - 19133:19133/udp
    environment:
      - VERSION=1.19.4
      - INIT_MEMORY=6G
      - MAX_MEMORY=8G
      - EULA=TRUE
      - TYPE=SPIGOT
      - DIFFICULTY=hard
      - ENFORCE_WHITELIST=TRUE
      - ENABLE_WHITELIST=TRUE
      - MAX_PLAYERS=10
      - VIEW_DISTANCE=10
      - ENABLE_COMMAND_BLOCK=false
      - FORCE_GAMEMODE=true
      - SPAWN_PROTECTION=4
      - TZ=Europe/Bucharest
      - NETWORK_COMPRESSION_THRESHOLD=-1
      - BUILD_FROM_SOURCE=true
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - survival-world:/data
      - survival-plugins:/plugins
      - dynmap-web:/web
    logging:
      driver: "json-file"
      options:
        max-size: "5m"

volumes:
  survival-world:
    external: true
    name: survival-world
  survival-plugins:
    external: true
    name: survival-plugins
  dynmap-web:
    external: true
    name: dynmap-web

networks:
  web-internal:
    name: web-internal
    external: true
