version: "3"

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - mc-net
    logging:
      driver: "json-file"
      options:
        max-size: "5m"

  db:
    image: mariadb:10.10
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD
    volumes:
      - db-storage:/var/lib/mysql
    networks:
      - mc-net
    logging:
      driver: "json-file"
      options:
        max-size: "5m"

  creative:
    image: itzg/minecraft-server
    environment:
      - VERSION=1.20.4
      - INIT_MEMORY=1G
      - MAX_MEMORY=3G
      - EULA=TRUE
      - TYPE=SPIGOT
      - ENFORCE_WHITELIST=TRUE
      - ENABLE_WHITELIST=TRUE
      - MAX_PLAYERS=10
      - VIEW_DISTANCE=10
      - FORCE_GAMEMODE=true
      - MODE=creative
      - NETWORK_COMPRESSION_THRESHOLD=-1
      - TZ=Europe/Bucharest
      - BUILD_FROM_SOURCE=true
      - LEVEL_TYPE=flat
      - GENERATE_STRUCTURES=false
    tty: true
    stdin_open: true
    restart: always
    networks:
      - mc-net
    volumes:
      - creative-world:/data
    logging:
      driver: "json-file"
      options:
        max-size: "5m"

  survival:
    image: itzg/minecraft-server
    environment:
      - VERSION=1.20.4
      - INIT_MEMORY=1G
      - MAX_MEMORY=3G
      - EULA=TRUE
      - TYPE=SPIGOT
      - DIFFICULTY=hard
      - ENFORCE_WHITELIST=TRUE
      - ENABLE_WHITELIST=TRUE
      - MAX_PLAYERS=10
      - VIEW_DISTANCE=10
      - ENABLE_COMMAND_BLOCK=false
      - FORCE_GAMEMODE=true
      - SPAWN_PROTECTION=4
      - TZ=Europe/Bucharest
      - NETWORK_COMPRESSION_THRESHOLD=-1
      - BUILD_FROM_SOURCE=true
      - MARIADB_SURVIVAL_PASSWORD
    tty: true
    stdin_open: true
    restart: always
    ports:
      - 19132:19132/udp
      - 19133:19133/udp
    networks:
      - mc-net
    volumes:
      - survival-world:/data
      - dynmap-web:/web
    logging:
      driver: "json-file"
      options:
        max-size: "5m"

  backups:
    image: itzg/mc-backup
    environment:
      RESTIC_HOSTNAME: minecraft-survival
      BACKUP_METHOD: restic
      BACKUP_INTERVAL: "2h"
      RCON_HOST: survival
      PAUSE_IF_NO_PLAYERS: true
      PRUNE_RESTIC_RETENTION: "--keep-daily 7 --keep-weekly 4 --keep-monthly 12"
      RESTIC_REPOSITORY: /backups
      RESTIC_PASSWORD:
    networks:
      - mc-net
    volumes:
      # mount the same volume used by server, but read-only
      - survival-world:/data:ro
      # use a host attached directory so that it in turn can be backed up
      # to external/cloud storage
      - survival-backup:/backups
    logging:
      driver: "json-file"
      options:
        max-size: "5m"


  mc-router:
    image: itzg/mc-router
    restart: always
    ports:
      - 25565:25565
    networks:
      - mc-net
    command: --mapping=minecraft.tbcl.ro=survival:25565,survival.minecraft.tbcl.ro=survival:25565,creative.minecraft.tbcl.ro=creative:25565,test.minecraft.tbcl.ro=192.168.3.1:25565
    logging:
      driver: "json-file"
      options:
        max-size: "5m"

volumes:
  survival-world:
    external: true
    name: minecraft-survival-world
  survival-backup:
    external: true
    name: minecraft-survival-world-backups
  dynmap-web:
    external: true
    name: minecraft-dynmap-web
  creative-world:
    external: true
    name: minecraft-creative-world
  db-storage:
    external: true
    name: minecraft-db-storage

networks:
  mc-net:
    name: mc-net
