version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
      - 19132:19132/udp
      - 19133:19133/udp
    environment:
      - VERSION=1.19.3
      - INIT_MEMORY=6G
      - MAX_MEMORY=8G
      - EULA=TRUE
      - TYPE=SPIGOT
      - DIFFICULTY=hard
      - ENFORCE_WHITELIST=TRUE
      - ENABLE_WHITELIST=TRUE
      - MAX_PLAYERS=10
      - VIEW_DISTANCE=10
      - ENABLE_COMMAND_BLOCK=false
      - FORCE_GAMEMODE=true
      - SPAWN_PROTECTION=4
      - TZ=Europe/Bucharest
      - NETWORK_COMPRESSION_THRESHOLD=-1
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - survival-01:/data
      - dynmap-web:/web
    logging:
      driver: "json-file"
      options:
        max-size: "5m"

volumes:
  survival-01:
  dynmap-web:
